package dev.emberline.core.graphics.spritekeys;

public enum SingleSpriteKey implements SpriteKey {
    STATS_BACKGROUND,
    NTDL_BACKGROUND,
    TDL_BACKGROUND,
    CANCEL_BUTTON,
    GENERIC_BUTTON,
    EMPTY_UPGRADE_LEVEL,
    FULL_UPGRADE_LEVEL,
    ADD_BUTTON,
    CHARS_ATLAS,
    ICE_BUTTON,
    FIRE_BUTTON,
    SMALL_BUTTON,
    BIG_BUTTON,
    UPGRADE_BUTTON,
    AIM_BUTTON,
    DISABLED_UPGRADE_BUTTON,
    SMALL_ICON,
    BIG_ICON,
    FIRE_ICON,
    ICE_ICON,
    // Tower dialog assets
    FIRE_RATE,
    DAMAGE,
    DAMAGE_AREA,
    PROJECTILE_SPEED,
    TOWER_RANGE,
    EFFECT_DURATION,
    BURN_EFFECT,
    SLOW_EFFECT,
    // Sign Buttons
    START_SIGN_BUTTON_1,
    START_SIGN_BUTTON_2,
    OPTIONS_SIGN_BUTTON_1,
    OPTIONS_SIGN_BUTTON_2,
    EXIT_SIGN_BUTTON_1,
    EXIT_SIGN_BUTTON_2,
    MENU_SIGN_BUTTON_1,
    MENU_SIGN_BUTTON_2,
    BACK_SIGN_BUTTON_1,
    BACK_SIGN_BUTTON_2,
    DEFAULT_SIGN_BUTTON,
    // Main Menu
    MENU_BACKGROUND,
    EMBERLINE_TITLE,
    // TowerPreBuild
    TOWER_PRE_BUILD,
    // Fog
    FOG,
    FOG_LEFT,
    FOG_RIGHT,
    FOG_TOP,
    FOG_BOTTOM,
    FOG_TOP_LEFT,
    FOG_TOP_RIGHT,
    FOG_BOTTOM_LEFT,
    FOG_BOTTOM_RIGHT,
    // In game gui
    TOPBAR_BACKGROUND,
    TOPBAR_OPTIONS_BUTTON_1,
    TOPBAR_OPTIONS_BUTTON_2,
    // Game Over
    GAME_OVER_BACKGROUND,
    GAME_OVER,
    // OPTIONS
    OPTIONS_WINDOW_BACKGROUND
}
